- name: install MongoDB component
  hosts: mongodb
  become: yes
  tasks:
    - name: copy mongodb repo file 
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo
    - name: Install mongodb
      ansible.builtin.yum:
        name: mongodb-org 
        state: installed
    - name: start and enable mongodb
      ansible.builtin.service:
        name: mongodb
        state: started 
        enabled: yes
    - name: enable remote connections to mogodb
      ansible.builtin.replace: 
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
    - name: restart mongod
      ansible.builtin.service:
        name: mongodb
        state: restarted 
